import { Language } from '../../localization/translations';

import { story_10012001StoryTranslations } from './story-10012001_i18n';
import { story_10012002StoryTranslations } from './story-10012002_i18n';
import { story_10012003StoryTranslations } from './story-10012003_i18n';
import { story_10012004StoryTranslations } from './story-10012004_i18n';
import { story_10012005StoryTranslations } from './story-10012005_i18n';
import { story_10012006StoryTranslations } from './story-10012006_i18n';
import { story_10012007StoryTranslations } from './story-10012007_i18n';
import { story_10012008StoryTranslations } from './story-10012008_i18n';
import { story_3StoryTranslations } from './story-3_i18n';
import { story_4StoryTranslations } from './story-4_i18n';
import { story_583921467StoryTranslations } from './story-583921467_i18n';
import { story_745829103StoryTranslations } from './story-745829103_i18n';
import { story_7481296StoryTranslations } from './story-7481296_i18n';
import { story_8273910265StoryTranslations } from './story-8273910265_i18n';
import { story_847362910StoryTranslations } from './story-847362910_i18n';
import { story_847362951StoryTranslations } from './story-847362951_i18n';
import { story_8743921042StoryTranslations } from './story-8743921042_i18n';
import { story_8923745610923StoryTranslations } from './story-8923745610923_i18n';
import { story_892746531StoryTranslations } from './story-892746531_i18n';
import { story_9123457712345StoryTranslations } from './story-9123457712345_i18n';
import { story_9845237719284StoryTranslations } from './story-9845237719284_i18n';
import { story_9932045517721StoryTranslations } from './story-9932045517721_i18n';

interface StoryTranslations {
  title: string;
  description: string;
  author: string;
  nodes: {
    [nodeId: string]: {
      title: string;
      narration: string;
      choices: {
        [choiceId: string]: {
          text: string;
          description?: string;
        };
      };
    };
  };
}

/**
 * Central registry of all story translations
 * Auto-generated by scripts/generate-translations.js
 */
export const storyTranslationsRegistry: Record<
  string,
  Record<Language, StoryTranslations>
> = {
  'story-10012001': story_10012001StoryTranslations,
  'story-10012002': story_10012002StoryTranslations,
  'story-10012003': story_10012003StoryTranslations,
  'story-10012004': story_10012004StoryTranslations,
  'story-10012005': story_10012005StoryTranslations,
  'story-10012006': story_10012006StoryTranslations,
  'story-10012007': story_10012007StoryTranslations,
  'story-10012008': story_10012008StoryTranslations,
  'story-3': story_3StoryTranslations,
  'story-4': story_4StoryTranslations,
  'story-583921467': story_583921467StoryTranslations,
  'story-745829103': story_745829103StoryTranslations,
  'story-7481296': story_7481296StoryTranslations,
  'story-8273910265': story_8273910265StoryTranslations,
  'story-847362910': story_847362910StoryTranslations,
  'story-847362951': story_847362951StoryTranslations,
  'story-8743921042': story_8743921042StoryTranslations,
  'story-8923745610923': story_8923745610923StoryTranslations,
  'story-892746531': story_892746531StoryTranslations,
  'story-9123457712345': story_9123457712345StoryTranslations,
  'story-9845237719284': story_9845237719284StoryTranslations,
  'story-9932045517721': story_9932045517721StoryTranslations,
};

/**
 * Get translations for a specific story
 */
export function getStoryTranslations(
  storyId: string,
): Record<Language, StoryTranslations> | undefined {
  return storyTranslationsRegistry[storyId];
}

/**
 * Check if a story has translations
 */
export function hasStoryTranslations(storyId: string): boolean {
  return storyId in storyTranslationsRegistry;
}
